databases:
  - name: cast-app-database
    databaseName: cast_app_database
    user: cast_app_database_user
    plan: free
services:
  - type: web
    plan: free
    name: investment_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -e production -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cast_app_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
