default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: cast_app_development

test:
  <<: *default
  database: cast_app_test

production:
  <<: *default
  database: cast_app_production
  username: cast_app
  password: <%= ENV["CAST_APP_DATABASE_PASSWORD"] %>
